
# Site settings
title: Snagata
email: teo.dragovic@gmail.com
permalink: /log/:year/:month/:day/:title/
date_format: "%F"
description: "Training log"
baseurl: "/snagata" # the subpath of your site, e.g. /blog
url: "https://teodragovic.com" # the base hostname & protocol for your site

collections:
  old2013:
    output: true
    permalink: /:collection/:name
  old2014:
    output: true
    permalink: /:collection/:name
  old2015:
    output: true
    permalink: /:collection/:name
  old2016:
    output: true
    permalink: /:collection/:name
  old2017:
    output: true
    permalink: /:collection/:name
  old2018:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown

kramdown:
  input: GFM

incremental: false

gems: [jekyll-paginate]
paginate: 20
paginate_path: "page:num/"

exclude: [backup, Rakefile, node_modules]

sass:
  sass_dir: _sass
  style: compressed

# Versioning for static assets
css: 9
js: 1
sw: 25
